MotoGP/MotoGP/Models/ViewModels/SelectRaceViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MotoGP.Models.ViewModels
{
    public class SelectRaceViewModel
    {
        public int raceID;
        public Race Race { get; set; }
        public SelectList Races { get; set; }

    }
}

MotoGP/MotoGP/Controllers/InfoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MotoGP.Models;
using System.Xml.Linq;
using MotoGP.Data;
using MotoGP.Models.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace MotoGP.Controllers
{
    public class InfoController : Controller
    {
        private readonly GPContext _context;
        public InfoController(GPContext context)
        {
            _context = context;
        }


        public IActionResult ListRaces()
        {
            ViewData["Title"] = "Races";
            ViewData["BannerNr"] = 0;
            var races = _context.Races
                .OrderBy(r => r.Date)
                .ToList<Race>();
            return View(races);
        }

        public IActionResult BuildMap()
        {
            /*Race race1 = new Race();
            Race race2 = new Race();
            Race race3 = new Race();

            race1.RaceID = 1;
            race1.Name = "Assen";
            race1.X =517;
            race1.Y =19;

            race2.RaceID = 2;
            race2.Name = "Losail Circuit";
            race2.X =859;
            race2.Y = 249;

            race3.RaceID = 3;
            race3.Name = "Autódromo Termas de Río Hondo";
            race3.X =194;
            race3.Y =428;

            var races = new List<Race> { race1, race2, race3};

            ViewData["BannerNr"] = 3;
            ViewData["Races"] = races;
            ViewData["Title"] = "Races on map";*/
            var races = _context.Races.ToList<Race>();
            return View(races);
        }
        public IActionResult ShowRace(int id)
        {
            Race race = _context.Races
                .Where(r => r.RaceID == id)
                .FirstOrDefault();
            return View(race);
        }
        public IActionResult ListRiders()
        {
            var riders = _context.Riders.OrderBy(r => r.Number).ToList();
            return View(riders);
        }
        public IActionResult SelectRace(int raceID = 0)
        {
            var selectRaceViewModel = new SelectRaceViewModel();
            if (raceID != 0)
            {
                selectRaceViewModel.Race = _context.Races.SingleOrDefault(r => r.RaceID == raceID);
            }
            /*else
            {
                selectRaceViewModel.Races = new SelectList(
                    _context.Races
                    .OrderBy(m => m.Name)
                    , "RaceID", "Name");
            }*/

            var races = new SelectList(_context.Races.OrderBy(m => m.Name), "RaceID", "Name");
            selectRaceViewModel.Races = races;

            return View(selectRaceViewModel);
        }

        public IActionResult ListTeams()
        {
            var teams = _context.Teams.Include(t => t.Riders).ToList();
            return View(teams);
        }
        public IActionResult ListTeamsRiders(int id = 0)
        {
            var selectTeamViewModel = new SelectTeamViewModel();
            selectTeamViewModel.Teams= _context.Teams.ToList();
            
            if (id != 0)
            {
                selectTeamViewModel.Riders = _context.Riders.Where(r=>r.TeamID== id).ToList();
            }

            return View(selectTeamViewModel);
        }
    }
}

MotoGP/MotoGP/Views/Info/BuildMap.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Race>
@{
   
}
<div>
    
    <img alt="Map with races" src="~/images/banners/map.png" usemap="#workmap"/>
    
    <map name="workmap">
        
        @{
            
            foreach (var race in Model)
            {

                <area shape="circle" coords="@race.X, @race.Y, 100" alt=@race.Name href=@Url.Action("ShowRace","Info", new { id = race.RaceID }) />
                
            
            }
            }
        
    </map>
    <p>

   
    <a asp-controller="Home" asp-action="Menu">
        Back
    </a>
    </p>
</div>

MotoGP/MotoGP/Views/Info/ListRaces.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Race>
@{
    List<String> doneMonths = new List<string>();
}
<div>
    <div>
        @{
            foreach (var race in Model)
            {
                String month = char.ToUpper(@race.Date.ToString("MMMM")[0]) + @race.Date.ToString("MMMM").Substring(1);

                if (!doneMonths.Contains(month))
                {
                    <h2>@month</h2>
                    doneMonths.Add(month);
                }
                <p style="margin: 0px;padding: 0px">@(Html.DisplayFor(modelItem => race.Date)) <a asp-controller="Info" asp-action="ShowRace" asp-route-id="@race.RaceID">@race.Name</a> </p>
            }
        }
    </div>
    <p>
        <a asp-controller="Home" asp-action="Menu">Back</a> | 
        <a asp-controller="Info" asp-action="BuildMap">Races on map</a> | 
        <a asp-controller="Info" asp-action="SelectRace">One by one</a>
    </p>
</div>

MotoGP/MotoGP/Views/Info/ListRiders.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Rider>
@{
    ViewData["Title"] = "Riders";
    ViewData["BannerNr"] = 1;
}
<div style="display: flex;flex-wrap: wrap">
    @foreach (var item in Model) {
        
        string sourcePicture = $"/images/riders/{item.Number}.jpg";
        string sourceFlag = $"/images/flags/{item.CountryID}.png";

        <div style="width: 30%;">
            <div class="card">
            
                <img src=@sourcePicture />
            
            <div >
                
                <img src=@sourceFlag/>
                <h2 style="display:inline-block;text-align:right">@item.Number</h2>
                <p style="color:darkgray;">@item.FirstName @item.LastName</p>
            </div>
        </div>
        </div>
    }
    
</div>

MotoGP/MotoGP/Views/Info/ListTeams.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Team>
@{
    ViewData["Title"] = "Teams";
    ViewData["BannerNr"] = 2;
}

<div style ="display: flex;flex-wrap: wrap">
    @foreach(var item in Model)
    {
        var source = $"/images/teams/{item.Logo}";
        <div style="width: 30%;">
            <div class="card">
                <figure style="background-color:lightgray;text-align:center;padding-top:20px;">
                    <img src=@source alt=@item.Name />
                    <figcaption>@item.Name</figcaption>
                    <ul style="padding:5px;list-style-type:none;">
                    @foreach(var rider in item.Riders)
                    {
                        <li>@rider.FirstName @rider.LastName</li>
                    }
                </ul>
                </figure> 
                
            </div>
        </div>
    }
    <p><a asp-action="ListTeamsRiders" asp-controller="Info">Teams & Riders</a></p>
</div>

MotoGP/MotoGP/Views/Info/ListTeamsRiders.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model MotoGP.Models.ViewModels.SelectTeamViewModel
@{
    ViewData["Title"] = "Teams & Riders";
    ViewData["BannerNr"] = 2;
}

<div>
    <div>
    @foreach(var item in Model.Teams)
    {
        var source = $"/images/teams/{item.Logo}";
        <div style="background-color:lightgray;padding:5px;display:inline;">
            
                    <a asp-controller="Info" asp-action="ListTeamsRiders" asp-route-id="@item.TeamID"><img src=@source /></a>
                    
          
            
        </div>
    }
    </div>
    @if (Model.Riders != null)
    {
        <div style="display: flex;flex-wrap: wrap">
            @foreach (var item in Model.Riders)
            {

                string sourcePicture = $"/images/riders/{item.Number}.jpg";
                string sourceFlag = $"/images/flags/{item.CountryID}.png";

                <div style="width: 30%;">
                    <div class="card" style="style=" background-color:lightgray;text-align:center;">

                        <img src=@sourcePicture />

                        <div>

                            <img src=@sourceFlag />
                            <h2 style="display:inline-block;text-align:right">@item.Number</h2>
                            <p style="color:darkgray;">@item.FirstName @item.LastName</p>
                        </div>
                    </div>
                </div>
            }

        </div>
    }
    
    <p><a asp-controller="Info" asp-action="ListTeams">Back</a></p>
</div>

MotoGP/MotoGP/Views/Info/SelectRace.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model MotoGP.Models.ViewModels.SelectRaceViewModel
@{
    //var races = (IEnumerable<SelectListItem>)ViewData["Races"];
}
<div>
    
    <form asp-controller="Info" asp-action="SelectRace" method="get">
        <select asp-for="raceID" asp-items=@Model.Races onchange="this.form.submit()">
        <option value="0">~~Select a race~~</option>
    </select>
    
    </form>
    @if(Model.Race != null){
        var source = $"/images/races/{Model.Race.RaceID}.jpg";
        <img src=@source alt=@Model.Race.Name/>
        <div>
            <p>@Model.Race.Name - @Model.Race.Country</p>
            <p>@Html.DisplayNameFor(model =>model.Race.Length): @Html.DisplayFor(model =>model.Race.Length) m</p>
            <p>@Html.DisplayNameFor(model =>model.Race.Date): @Html.DisplayFor(model =>model.Race.Date)</p>
            <br/>
            <p>@Model.Race.Description</p>
        </div>
    }

    <p><a asp-action="ListRaces" asp-controller="Info">Back</a></p>
</div>

MotoGP/MotoGP/Views/Info/ShowRace.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Race
@{
    ViewData["Title"] = $"Race - {Model.Name}";
    String source = $"/images/races/{Model.RaceID}.jpg";
}
<div>
    <h2>
        @Model.Date - @Model.Country
    </h2>
    <img src=@source alt=@Model.Name />
    <p>@Model.Description</p>
    <p><a asp-controller="Info" asp-action="ListRaces">Back</a></p>

</div>