MusicStore/MusicStore/MusicStore/Models/BusinessLogic/ShoppingCart.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicStore.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicStore.Models
{
    public class ShoppingCart
    {
        private StoreContext _context;
        string _cartKey { get; set; }
        
        public ShoppingCart (HttpContext httpContext, StoreContext context)
        {
            _cartKey = GetCartKey(httpContext);
            _context = context;
        }

        private string GetCartKey(HttpContext httpContext)
        {
            if (httpContext.Session.GetString("CartKey") == null)
            {
                Guid tempCartKey = Guid.NewGuid();
                httpContext.Session.SetString("CartKey", tempCartKey.ToString());
            }
            return httpContext.Session.GetString("CartKey");
        }

        public void AddToCart(Album album)
        {
            // Get the matching cart and album instances
            var cartItem = _context.CartItems.SingleOrDefault(
                c => c.CartKey == _cartKey
                && c.AlbumID == album.AlbumID);

            if (cartItem == null)
            {
                // Create a new cart item if no cart item exists
                cartItem = new CartItem
                {
                    AlbumID = album.AlbumID,
                    CartKey = _cartKey,
                    Count = 1,
                    DateCreated = DateTime.Now
                };
                _context.CartItems.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart, 
                // then add one to the quantity
                cartItem.Count++;
            }
            _context.SaveChanges();
        }
        

        public void EmptyCart()
        {
            var cartItems = _context.CartItems.Where(
                c => c.CartKey == _cartKey);

            foreach (var cartItem in cartItems)
            {
                _context.CartItems.Remove(cartItem);
            }
            _context.SaveChanges();
        }

        public List<CartItem> GetCartItems()
        {
            var cartItems = _context.CartItems.Include(c => c.Album).ThenInclude(c => c.Artist).Where(
                c => c.CartKey == _cartKey);
                
            return cartItems.ToList();
        }

        public int GetCount()
        {
            // Get the count of each item in the cart and sum them up
            int? count = (from c in _context.CartItems
                          where c.CartKey == _cartKey
                          select (int?)c.Count).Sum();
            // Return 0 if all entries are null
            return count ?? 0;
        }

        public void CreateOrderItems(Order order)
        {
            var cartItems = GetCartItems();
            // Iterate over the items in the cart, 
            // adding the order details for each
            foreach (var item in cartItems)  {
                var orderItem = new OrderItem {
                    AlbumID = item.AlbumID,
                    OrderID = order.OrderID,
                    UnitPrice = item.Album.Price,
                    Quantity = item.Count
                };

                _context.OrderItems.Add(orderItem);
            }
            
            // Save the orderitems
            _context.SaveChanges();
            // Empty the shopping cart
            EmptyCart();

            return;
        }
        //SELFMADE
        public void RemoveFromCart(int id)
        {
            var cartItem = _context.CartItems.SingleOrDefault(c => c.CartItemID == id);
            if (cartItem != null)
            {
                _context.CartItems.Remove(cartItem);
                _context.SaveChanges();
            }
        }

        public void AddOneToCart(int id)
        {
            var cartItem = _context.CartItems.SingleOrDefault(c => c.CartItemID == id);
            cartItem.Count = cartItem.Count + 1;
            try
            {
                _context.Update(cartItem);
                _context.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                throw;

            }
            

        }
        public void RemoveOneFromCart(int id)
        {
            var cartItem = _context.CartItems.SingleOrDefault(c => c.CartItemID == id);
            cartItem.Count = cartItem.Count - 1;

            if (cartItem.Count > 0)
            {
                try
                {
                    _context.Update(cartItem);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;

                }
            }
            else
            {
                try
                {
                    _context.Remove(cartItem);
                    _context.SaveChanges();
                }
                catch (Exception)
                {
                    throw;

                }

            }

           
        }

    }
}

MusicStore/MusicStore/MusicStore/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicStore.Data;
using MusicStore.Models;

namespace MusicStore.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        private readonly StoreContext _context;

        public CheckoutController(StoreContext context)
        {
            _context = context;
        }

        // GET: Admin/Checkout/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Checkout/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderID,Address,Name,OrderDate,Username")] Order order)
        {
            

            //if (ModelState.IsValid)
            //{
                order.Username = HttpContext.User.Identity.Name;
                order.OrderDate = DateTime.Now;

                _context.Add(order);
                _context.SaveChanges();

                var cart = new ShoppingCart(HttpContext, _context);
                cart.CreateOrderItems(order);

                await _context.SaveChangesAsync();
                return RedirectToAction("Complete", new { id = order.OrderID });
            //}
            //return View(order);
        }


        public async Task<IActionResult> Complete(int id)
        {
            ViewData["OrderNr"] = id;
            return View();
        }
    }
}

MusicStore/MusicStore/MusicStore/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using MusicStore.Data;
using MusicStore.Models;

namespace MusicStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly StoreContext _context;
        private HttpContext httpContext;

        public ShoppingCartController(StoreContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            
            var shoppingCart = new ShoppingCart(HttpContext, _context);
            var cartItems = shoppingCart.GetCartItems();
            return View(cartItems);
        }
        public IActionResult AddToCart(int id)
        {
            var shoppingCart = new ShoppingCart(HttpContext, _context);
            var album = _context.Albums.SingleOrDefault(a=>a.AlbumID== id);
            shoppingCart.AddToCart(album);
            return RedirectToAction("Index");
            
        }
        public IActionResult RemoveFromCart(int id)
        {
            var shoppingCart = new ShoppingCart(HttpContext, _context);
            shoppingCart.RemoveFromCart(id);
            return RedirectToAction("Index");
        }
        public IActionResult AddOne(int id)
        {
            var shoppingCart = new ShoppingCart(HttpContext, _context);
            shoppingCart.AddOneToCart(id);
            return RedirectToAction("Index");
        }
        public IActionResult RemoveOne(int id)
        {
            var shoppingCart = new ShoppingCart(HttpContext, _context);
            shoppingCart.RemoveOneFromCart(id);
            return RedirectToAction("Index");
        }
    }
}

MusicStore/MusicStore/MusicStore/Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicStore.Data;

namespace MusicStore.Controllers
{
    public class StoreController : Controller
    {
        private readonly StoreContext _context;

        public StoreController(StoreContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> ListGenres()
        {
            return View(await _context.Genres.OrderBy(g=>g.Name).ToListAsync());
            
        }
        public async Task<IActionResult> ListAlbums(int id)
        {

            return View(await _context.Albums.OrderBy(g => g.Title).Where(g=>g.GenreID==id).ToListAsync());

        }
        public async Task<IActionResult> Details(int id)
        {

            return View(await _context.Albums.Include(a=>a.Genre).Include(a=>a.Artist).SingleAsync(a=>a.AlbumID==id));
        }
    }
}

MusicStore/MusicStore/MusicStore/Views/ShoppingCart/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<CartItem>
@{
    ViewData["Title"] = "Shopping Cart";
}
<div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Album.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Album.Price) (each)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Count)
                </th>
                <th>
                    Total
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                var total = item.Count * item.Album.Price;
                <tr>
                    <td>
                        <a asp-action="Details" asp-controller="Store" asp-route-id="@item.AlbumID">@Html.DisplayFor(modelItem => item.Album.Title)</a>
                        
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Album.Price) euro
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Count)
                    </td>
                    <td>
                        @total euro
                    </td>
                    <td>
                        <a asp-controller="ShoppingCart" asp-action="AddOne" asp-route-id="@item.CartItemID">+</a> |
                        <a asp-controller="ShoppingCart" asp-action="RemoveOne" asp-route-id="@item.CartItemID">-</a> |
                        <a asp-controller="ShoppingCart" asp-action="RemoveFromCart" asp-route-id="@item.CartItemID">Remove</a>
                    </td>
                </tr>
            }
            <tr>
                <td style="font-weight:bold;">Total</td>
                <td></td>
                <td></td>
                @{
                    var cartTotal = Model.Sum(m => m.Count * m.Album.Price);
                    <td style="font-weight:bold;">@cartTotal euro</td>
                }
                <td></td>
            </tr>
        </tbody>
    </table>
    <p>
        <a asp-controller="Checkout" asp-action="Create">Checkout</a> | <a asp-controller="Home" asp-action="Index">Back to Home</a>
    </p>
</div>